#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true
#    username: root
#    password: Niki@123
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
      
server:
  port: 8080
spring:
  data:
    momgodb:
      uri: mongodb://localhost:27017/TaskDB

logging:
  level:
    org:
      springframework:
        root: ERROR
    com:
      dushi:
        taskService: DEBUG




